[package]
name = "disc_image"
version = "0.1.0"
authors = ["Cary Haynie <cary.haynie@gmail.com>"]

[dependencies]
disc_image-derive = { path = "disc_image-derive" }
nom = { version = "^2.1", features = [ "regexp" ] }